// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DataAccess.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20220830212934_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Core.Entities.Concrete.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Core.Entities.Concrete.GroupClaim", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupId", "ClaimId");

                    b.ToTable("GroupClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Code = "tr-TR",
                            Name = "Türkçe"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Code = "en-US",
                            Name = "English"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Core.Entities.Concrete.MobileLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsSend")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId", "Provider");

                    b.ToTable("MobileLogins");
                });

            modelBuilder.Entity("Core.Entities.Concrete.OperationClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Translate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LangId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Translates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("76743ccd-878e-4031-9148-24a1b4ce627c"),
                            Code = "Login",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Giriş"
                        },
                        new
                        {
                            Id = new Guid("725be0b3-8f85-4f3b-a80d-3338faf4366d"),
                            Code = "Email",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "E posta"
                        },
                        new
                        {
                            Id = new Guid("015157b2-0393-4567-89d5-3d766ffd56d6"),
                            Code = "Password",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Parola"
                        },
                        new
                        {
                            Id = new Guid("cd1e192c-1493-464f-8146-717e0b200868"),
                            Code = "Update",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Güncelle"
                        },
                        new
                        {
                            Id = new Guid("2cdd0f2e-53de-4b3d-bd51-4751b43444c2"),
                            Code = "Delete",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Sil"
                        },
                        new
                        {
                            Id = new Guid("abb3252f-ae18-4581-a3b3-cc82584386eb"),
                            Code = "UsersGroups",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kullanıcının Grupları"
                        },
                        new
                        {
                            Id = new Guid("333c2a35-9174-4744-88d3-f6fce25c8d2c"),
                            Code = "UsersClaims",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kullanıcının Yetkileri"
                        },
                        new
                        {
                            Id = new Guid("a63da07b-1dcd-40ec-9946-24ff463cf2c2"),
                            Code = "Create",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yeni"
                        },
                        new
                        {
                            Id = new Guid("3c68afb2-9031-4ea9-bc96-b724c0d778e0"),
                            Code = "Users",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kullanıcılar"
                        },
                        new
                        {
                            Id = new Guid("154fcebc-78a6-4d8e-bdc1-b33db364117b"),
                            Code = "Groups",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Gruplar"
                        },
                        new
                        {
                            Id = new Guid("4a4daca7-f419-406c-a26e-fd8dd3dac2e9"),
                            Code = "Login",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Login"
                        },
                        new
                        {
                            Id = new Guid("32c8181e-e9b7-4fa0-839f-8344f8df2c58"),
                            Code = "Email",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Email"
                        },
                        new
                        {
                            Id = new Guid("98e00a57-3a6e-47dc-8bf6-2c4a03568b0b"),
                            Code = "Password",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Password"
                        },
                        new
                        {
                            Id = new Guid("02140d08-2260-4e0c-871c-bbb491a94a2f"),
                            Code = "Update",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Update"
                        },
                        new
                        {
                            Id = new Guid("412ca3fe-1c68-49f9-a35e-5a23af723856"),
                            Code = "Delete",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Delete"
                        },
                        new
                        {
                            Id = new Guid("64d7df14-c1a1-4b2f-b65b-95429f3872d6"),
                            Code = "UsersGroups",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "User's Groups"
                        },
                        new
                        {
                            Id = new Guid("5a0ac35c-6ab8-44a1-9c03-0804197028eb"),
                            Code = "UsersClaims",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "User's Claims"
                        },
                        new
                        {
                            Id = new Guid("32f8010b-95bb-45f4-9563-552e88f98e1d"),
                            Code = "Create",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Create"
                        },
                        new
                        {
                            Id = new Guid("336cf876-c289-418a-85fd-1f1fb3de3a32"),
                            Code = "Users",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Users"
                        },
                        new
                        {
                            Id = new Guid("d8f8d673-3a1a-44b2-8188-53090e20c51e"),
                            Code = "Groups",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Groups"
                        },
                        new
                        {
                            Id = new Guid("43d08270-fb6f-4821-8de4-7a5e1f9949ad"),
                            Code = "OperationClaim",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Operasyon Yetkileri"
                        },
                        new
                        {
                            Id = new Guid("8c88b7d3-3d35-4cde-941f-ea756f79fe98"),
                            Code = "OperationClaim",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Operation Claim"
                        },
                        new
                        {
                            Id = new Guid("d85b8a2a-9a55-471c-8f26-4f1fb1b1e028"),
                            Code = "Languages",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Diller"
                        },
                        new
                        {
                            Id = new Guid("3414d895-00dc-4497-a8d9-43089b35aa14"),
                            Code = "Languages",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Languages"
                        },
                        new
                        {
                            Id = new Guid("71d3e1af-f440-42dd-ad15-712ac2a4f982"),
                            Code = "TranslateWords",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Dil Çevirileri"
                        },
                        new
                        {
                            Id = new Guid("1ac3574e-56e6-4030-ab0c-3e5346bb6038"),
                            Code = "TranslateWords",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Translate Words"
                        },
                        new
                        {
                            Id = new Guid("78398f3a-2ed1-451a-8ba4-38863ea9ca88"),
                            Code = "Management",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yönetim"
                        },
                        new
                        {
                            Id = new Guid("6fe0ea27-2579-43d4-9b1b-1f091307071c"),
                            Code = "Management",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Management"
                        },
                        new
                        {
                            Id = new Guid("42d619fc-0226-4bc0-9703-51b0e30fb183"),
                            Code = "AppMenu",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Uygulama"
                        },
                        new
                        {
                            Id = new Guid("97e8e13f-c0f5-4bff-8a09-34e451e1768e"),
                            Code = "AppMenu",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Application"
                        },
                        new
                        {
                            Id = new Guid("a3deb409-01a8-4dbf-ba87-6556c17a9fa8"),
                            Code = "Added",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Başarıyla Eklendi."
                        },
                        new
                        {
                            Id = new Guid("2d1b6120-76ce-418f-9bf2-66739761d306"),
                            Code = "Added",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Successfully Added."
                        },
                        new
                        {
                            Id = new Guid("49f8568c-b912-4eeb-a34d-18359745cd32"),
                            Code = "Updated",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Başarıyla Güncellendi."
                        },
                        new
                        {
                            Id = new Guid("eeb7c0aa-91af-4e56-b79a-a4276079a8af"),
                            Code = "Updated",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Successfully Updated."
                        },
                        new
                        {
                            Id = new Guid("da2c76d5-f31a-4a6f-9817-1026d6d20856"),
                            Code = "Deleted",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Başarıyla Silindi."
                        },
                        new
                        {
                            Id = new Guid("17268f46-bb84-402f-aee6-1a6105afd168"),
                            Code = "Deleted",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Successfully Deleted."
                        },
                        new
                        {
                            Id = new Guid("ccc1f256-947f-40d9-95d6-6a85022ebcc6"),
                            Code = "OperationClaimExists",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Bu operasyon izni zaten mevcut."
                        },
                        new
                        {
                            Id = new Guid("f2be768d-83ed-4d38-8bde-5ba8b122582e"),
                            Code = "OperationClaimExists",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "This operation permit already exists."
                        },
                        new
                        {
                            Id = new Guid("249c8d0f-f856-45b6-828b-1d5a971cc4e9"),
                            Code = "StringLengthMustBeGreaterThanThree",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Lütfen En Az 3 Karakterden Oluşan Bir İfade Girin."
                        },
                        new
                        {
                            Id = new Guid("87cacac4-4b1c-458a-8406-6cf03830e387"),
                            Code = "StringLengthMustBeGreaterThanThree",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Please Enter A Phrase Of At Least 3 Characters."
                        },
                        new
                        {
                            Id = new Guid("ca955d5e-3cc0-4920-802a-706246957f15"),
                            Code = "CouldNotBeVerifyCid",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kimlik No Doğrulanamadı."
                        },
                        new
                        {
                            Id = new Guid("b0591ee6-c660-4b24-a873-3c5a5ede6253"),
                            Code = "CouldNotBeVerifyCid",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Could not be verify Citizen Id"
                        },
                        new
                        {
                            Id = new Guid("1a5acc97-fd94-4b39-aa1a-c5382237d9c6"),
                            Code = "VerifyCid",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kimlik No Doğrulandı."
                        },
                        new
                        {
                            Id = new Guid("47e7d151-81f7-45cb-8d4c-c52c5ca46181"),
                            Code = "VerifyCid",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Verify Citizen Id"
                        },
                        new
                        {
                            Id = new Guid("f3dda3d0-b497-4a67-8b9f-eacca55eeb85"),
                            Code = "AuthorizationsDenied",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yetkiniz olmayan bir alana girmeye çalıştığınız tespit edildi."
                        },
                        new
                        {
                            Id = new Guid("6dbf59ce-da65-4787-9841-7806d157ba96"),
                            Code = "AuthorizationsDenied",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "It has been detected that you are trying to enter an area that you do not have authorization."
                        },
                        new
                        {
                            Id = new Guid("4b696290-e789-4417-b54b-d8711686ef69"),
                            Code = "UserNotFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kimlik Bilgileri Doğrulanamadı. Lütfen Yeni Kayıt Ekranını kullanın."
                        },
                        new
                        {
                            Id = new Guid("5643f029-af63-47cb-a28a-552e1fc2d9a9"),
                            Code = "UserNotFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Credentials Could Not Verify. Please use the New Registration Screen."
                        },
                        new
                        {
                            Id = new Guid("424db20e-e520-4c1c-9294-bbd118142b47"),
                            Code = "PasswordError",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kimlik Bilgileri Doğrulanamadı, Kullanıcı adı ve/veya parola hatalı."
                        },
                        new
                        {
                            Id = new Guid("aa8f9fdf-7312-499d-a747-9b9c72cc14b4"),
                            Code = "PasswordError",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Credentials Failed to Authenticate, Username and / or password incorrect."
                        },
                        new
                        {
                            Id = new Guid("83609bf3-1c7a-4413-baf7-3e1498b8a5da"),
                            Code = "SuccessfulLogin",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Sisteme giriş başarılı."
                        },
                        new
                        {
                            Id = new Guid("67d9f970-77e2-4d19-805c-38d736a7b67c"),
                            Code = "SuccessfulLogin",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Login to the system is successful."
                        },
                        new
                        {
                            Id = new Guid("557569b7-573f-499b-9232-f7b67201beff"),
                            Code = "SendMobileCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Lütfen Size SMS Olarak Gönderilen Kodu Girin!"
                        },
                        new
                        {
                            Id = new Guid("445157ff-d072-40cd-9334-e425040d9210"),
                            Code = "SendMobileCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Please Enter The Code Sent To You By SMS!"
                        },
                        new
                        {
                            Id = new Guid("744a653c-e632-4667-a277-cab6622ac52f"),
                            Code = "NameAlreadyExist",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Oluşturmaya Çalıştığınız Nesne Zaten Var."
                        },
                        new
                        {
                            Id = new Guid("2c8889db-aa43-44d7-b4fc-883597b95956"),
                            Code = "NameAlreadyExist",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "The Object You Are Trying To Create Already Exists."
                        },
                        new
                        {
                            Id = new Guid("7881d53a-19c1-4309-8a0a-82209e5e0d96"),
                            Code = "WrongCID",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Vatandaşlık No Sistemimizde Bulunamadı. Lütfen Yeni Kayıt Oluşturun!"
                        },
                        new
                        {
                            Id = new Guid("ac7da914-10ba-4873-94ed-a22668388315"),
                            Code = "WrongCID",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Citizenship Number Not Found In Our System. Please Create New Registration!"
                        },
                        new
                        {
                            Id = new Guid("1d117708-24a7-421d-9162-45c5b76ff0d8"),
                            Code = "CID",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Vatandaşlık No"
                        },
                        new
                        {
                            Id = new Guid("a71c00ff-fd09-4a67-b275-c524e6747842"),
                            Code = "CID",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Citizenship Number"
                        },
                        new
                        {
                            Id = new Guid("e85b7294-902c-48c3-945e-1972b3f3a479"),
                            Code = "PasswordEmpty",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Parola boş olamaz!"
                        },
                        new
                        {
                            Id = new Guid("ef66fbb7-76e4-44a5-841d-18fda8671115"),
                            Code = "PasswordEmpty",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Password can not be empty!"
                        },
                        new
                        {
                            Id = new Guid("ddcdb660-283b-41b8-835f-9ba617009b40"),
                            Code = "PasswordLength",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Minimum 8 Karakter Uzunluğunda Olmalıdır!"
                        },
                        new
                        {
                            Id = new Guid("da887c58-0ce4-41c0-909a-f30fbb458f0e"),
                            Code = "PasswordLength",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Must be at least 8 characters long! "
                        },
                        new
                        {
                            Id = new Guid("ea0757cd-fac8-48de-a44d-710eee9e78d7"),
                            Code = "PasswordUppercaseLetter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "En Az 1 Büyük Harf İçermelidir!"
                        },
                        new
                        {
                            Id = new Guid("bcdbcf06-1872-471e-a59b-d6639bfde53a"),
                            Code = "PasswordUppercaseLetter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Must Contain At Least 1 Capital Letter!"
                        },
                        new
                        {
                            Id = new Guid("7c5164e3-4e00-4e49-b630-0bfc334c2726"),
                            Code = "PasswordLowercaseLetter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "En Az 1 Küçük Harf İçermelidir!"
                        },
                        new
                        {
                            Id = new Guid("9da21341-0ca5-481c-a0ca-071e62320715"),
                            Code = "PasswordLowercaseLetter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Must Contain At Least 1 Lowercase Letter!"
                        },
                        new
                        {
                            Id = new Guid("8b2400bd-186c-4afe-a9f9-c43d05cdcd8e"),
                            Code = "PasswordDigit",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "En Az 1 Rakam İçermelidir!"
                        },
                        new
                        {
                            Id = new Guid("2e15c2cf-8f94-493f-af63-50615a823cc5"),
                            Code = "PasswordDigit",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "It Must Contain At Least 1 Digit!"
                        },
                        new
                        {
                            Id = new Guid("d62439f1-ff7e-476e-84cc-ece5a89d491c"),
                            Code = "PasswordSpecialCharacter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "En Az 1 Simge İçermelidir!"
                        },
                        new
                        {
                            Id = new Guid("517098c6-f826-4d9a-87bb-3c473be8839a"),
                            Code = "PasswordSpecialCharacter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Must Contain At Least 1 Symbol!"
                        },
                        new
                        {
                            Id = new Guid("7d55cd3f-cd8d-473b-b689-672ac85b9a7f"),
                            Code = "SendPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yeni Parolanız E-Posta Adresinize Gönderildi."
                        },
                        new
                        {
                            Id = new Guid("651aed63-105b-490d-aee6-dcb277458ccb"),
                            Code = "SendPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Your new password has been sent to your e-mail address."
                        },
                        new
                        {
                            Id = new Guid("a7632a80-bf4d-45ee-866c-2127f4c4f014"),
                            Code = "InvalidCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Geçersiz Bir Kod Girdiniz!"
                        },
                        new
                        {
                            Id = new Guid("79425b23-2563-4837-8c06-3839ca6f0c15"),
                            Code = "InvalidCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "You Entered An Invalid Code!"
                        },
                        new
                        {
                            Id = new Guid("88c33f2c-7936-4d60-903e-cf6521a90c35"),
                            Code = "SmsServiceNotFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "SMS Servisine Ulaşılamıyor."
                        },
                        new
                        {
                            Id = new Guid("cb420163-9089-4543-957d-117395c9586a"),
                            Code = "SmsServiceNotFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Unable to Reach SMS Service."
                        },
                        new
                        {
                            Id = new Guid("34da00c3-4557-4aa3-a9de-78a3d14e0120"),
                            Code = "TrueButCellPhone",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Bilgiler doğru. Cep telefonu gerekiyor."
                        },
                        new
                        {
                            Id = new Guid("38983496-d989-4c2c-9028-259aa1baea2e"),
                            Code = "TrueButCellPhone",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "The information is correct. Cell phone is required."
                        },
                        new
                        {
                            Id = new Guid("47669c83-91a1-4807-9b34-d4468c154c78"),
                            Code = "TokenProviderException",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Token Provider boş olamaz!"
                        },
                        new
                        {
                            Id = new Guid("d7804e3f-8af7-49a2-8f93-87b290744266"),
                            Code = "TokenProviderException",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Token Provider cannot be empty!"
                        },
                        new
                        {
                            Id = new Guid("635f3748-6d11-4f3d-9ddc-5ec2b692fb98"),
                            Code = "Unknown",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Bilinmiyor!"
                        },
                        new
                        {
                            Id = new Guid("ac7c52cb-3940-4274-a8b4-e3637f7a7c65"),
                            Code = "Unknown",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Unknown!"
                        },
                        new
                        {
                            Id = new Guid("b23af6be-1f70-43c7-8d6b-ab9b3c76ff39"),
                            Code = "NewPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yeni Parola:"
                        },
                        new
                        {
                            Id = new Guid("aad98b91-ae17-4fec-a6a0-bc5ca9d0e2e5"),
                            Code = "NewPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "New Password:"
                        },
                        new
                        {
                            Id = new Guid("a704d73e-c48a-47a6-84b2-25869ee4514f"),
                            Code = "ChangePassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Parola Değiştir"
                        },
                        new
                        {
                            Id = new Guid("89db034b-620f-4165-9bbf-36ec08e74b80"),
                            Code = "ChangePassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Change Password"
                        },
                        new
                        {
                            Id = new Guid("648cd7c0-ee6c-4cb7-82c3-9d5aeee8548d"),
                            Code = "Save",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kaydet"
                        },
                        new
                        {
                            Id = new Guid("b5c99cb3-0991-4518-a1b2-c20e0980b5b9"),
                            Code = "Save",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Save"
                        },
                        new
                        {
                            Id = new Guid("1dd069de-fb34-4183-9635-2361df53d41f"),
                            Code = "GroupName",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Grup Adı"
                        },
                        new
                        {
                            Id = new Guid("eb9d4f9e-9792-4fb2-ac7a-f42002e62605"),
                            Code = "GroupName",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Group Name"
                        },
                        new
                        {
                            Id = new Guid("0892e1eb-90b9-46b6-b1eb-e7cf973b317d"),
                            Code = "FullName",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Tam Adı"
                        },
                        new
                        {
                            Id = new Guid("fda6bbe7-cedc-4510-a65f-dff4c4a0ce5d"),
                            Code = "FullName",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Full Name"
                        },
                        new
                        {
                            Id = new Guid("2ca6023a-bebe-418a-985d-c7527a1ab301"),
                            Code = "Address",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Adres"
                        },
                        new
                        {
                            Id = new Guid("71f8c95d-ebc2-4a46-8c11-02afeb3c01c4"),
                            Code = "Address",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Address"
                        },
                        new
                        {
                            Id = new Guid("97897b79-582a-454f-bc35-89ad55137278"),
                            Code = "Notes",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Notlar"
                        },
                        new
                        {
                            Id = new Guid("6a5ffedb-e371-426f-a818-54c069f38db5"),
                            Code = "Notes",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Notes"
                        },
                        new
                        {
                            Id = new Guid("af344899-a908-4f34-a4d7-65f8919e2c62"),
                            Code = "ConfirmPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Parolayı Doğrula"
                        },
                        new
                        {
                            Id = new Guid("ea401438-2bec-4269-9198-680cb993d69e"),
                            Code = "ConfirmPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Confirm Password"
                        },
                        new
                        {
                            Id = new Guid("c3180dc9-a42e-4a51-9d1f-6bc0937505bf"),
                            Code = "Code",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kod"
                        },
                        new
                        {
                            Id = new Guid("33bad072-f068-44ae-bab4-d11841d9e692"),
                            Code = "Code",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Code"
                        },
                        new
                        {
                            Id = new Guid("64e2e8ee-d6d6-4907-960f-9b237671fa8b"),
                            Code = "Alias",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Görünen Ad"
                        },
                        new
                        {
                            Id = new Guid("1e3740e2-9529-484d-a052-072fcf245d7a"),
                            Code = "Alias",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Alias"
                        },
                        new
                        {
                            Id = new Guid("5c8c66b8-21f0-46d4-a439-db08191cc9a9"),
                            Code = "Description",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Açıklama"
                        },
                        new
                        {
                            Id = new Guid("a3cec195-2e7f-4322-9675-579cf6b34c60"),
                            Code = "Description",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Description"
                        },
                        new
                        {
                            Id = new Guid("f0661ce7-ec1f-4fe8-99a5-6fce21c8cb86"),
                            Code = "Value",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Değer"
                        },
                        new
                        {
                            Id = new Guid("3bd440fe-a4ed-4696-9957-7ef0b3daecc9"),
                            Code = "Value",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Value"
                        },
                        new
                        {
                            Id = new Guid("339efe81-7c42-4030-8d81-9ffc472b0a2a"),
                            Code = "LangCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Dil Kodu"
                        },
                        new
                        {
                            Id = new Guid("5e6d21de-efe4-4e80-bbe0-a97f176a2ee4"),
                            Code = "LangCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Lang Code"
                        },
                        new
                        {
                            Id = new Guid("40daa094-add4-4680-b9ff-7bdc77ac586c"),
                            Code = "Name",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Adı"
                        },
                        new
                        {
                            Id = new Guid("8c2c8031-7e98-4123-9395-421d880d9bd8"),
                            Code = "Name",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Name"
                        },
                        new
                        {
                            Id = new Guid("49f55700-96b0-4e8b-bb1a-c60f530bbc86"),
                            Code = "MobilePhones",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Cep Telefonu"
                        },
                        new
                        {
                            Id = new Guid("3c061a84-225a-4d04-b615-13de986a759c"),
                            Code = "MobilePhones",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Mobile Phone"
                        },
                        new
                        {
                            Id = new Guid("7b383321-aba4-490d-85c7-15a1bca89193"),
                            Code = "NoRecordsFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kayıt Bulunamadı"
                        },
                        new
                        {
                            Id = new Guid("9ab97f3b-5ab5-4e19-9bb1-53770e1cf3bb"),
                            Code = "NoRecordsFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "No Records Found"
                        },
                        new
                        {
                            Id = new Guid("698cc22b-461f-43cd-9b06-7ed0bacb66fe"),
                            Code = "Required",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Bu alan zorunludur!"
                        },
                        new
                        {
                            Id = new Guid("2db9517a-84a2-4f3c-b91d-1306908aa208"),
                            Code = "Required",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "This field is required!"
                        },
                        new
                        {
                            Id = new Guid("d53a082b-077f-4905-b4ff-deff3e87f8af"),
                            Code = "Permissions",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Permissions"
                        },
                        new
                        {
                            Id = new Guid("afa651bc-b75b-411e-8742-bd89b8b879b7"),
                            Code = "Permissions",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "İzinler"
                        },
                        new
                        {
                            Id = new Guid("341ea206-144f-4a95-8506-4f2eb4daf8b8"),
                            Code = "GroupList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Grup Listesi"
                        },
                        new
                        {
                            Id = new Guid("f3b0e7d4-2c05-470b-ac2e-ecefe9984efa"),
                            Code = "GroupList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Group List"
                        },
                        new
                        {
                            Id = new Guid("fe6fc2b2-b71a-4ea5-8f98-b737f6fb1db0"),
                            Code = "GrupPermissions",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Grup Yetkileri"
                        },
                        new
                        {
                            Id = new Guid("d433767b-a76d-4c4b-8a1b-4b51ec4b8ffc"),
                            Code = "GrupPermissions",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Grup Permissions"
                        },
                        new
                        {
                            Id = new Guid("5af130b7-4179-417e-bdb2-9f529a32689d"),
                            Code = "Add",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Ekle"
                        },
                        new
                        {
                            Id = new Guid("6215c243-883f-4e13-b727-2b01f06963ca"),
                            Code = "Add",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Add"
                        },
                        new
                        {
                            Id = new Guid("3dd5375f-64fe-473f-a700-9d283d7e794f"),
                            Code = "UserList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kullanıcı Listesi"
                        },
                        new
                        {
                            Id = new Guid("7ed7874e-1bf3-40f5-bc79-85491d51de9c"),
                            Code = "UserList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "User List"
                        },
                        new
                        {
                            Id = new Guid("7ea943e5-7b8e-4897-9625-42d80febaade"),
                            Code = "OperationClaimList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yetki Listesi"
                        },
                        new
                        {
                            Id = new Guid("3caf5a5f-b6d2-4cd1-8b67-7bb5eb2426a2"),
                            Code = "OperationClaimList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "OperationClaim List"
                        },
                        new
                        {
                            Id = new Guid("04e3f431-e371-463b-b007-18590c7bb486"),
                            Code = "LanguageList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Dil Listesi"
                        },
                        new
                        {
                            Id = new Guid("9fedbe73-a9a3-4c7d-b93f-a8cdc43f655c"),
                            Code = "LanguageList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Language List"
                        },
                        new
                        {
                            Id = new Guid("b77d4cc7-5fea-496f-90b8-8818a44f20e0"),
                            Code = "TranslateList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Dil Çeviri Listesi"
                        },
                        new
                        {
                            Id = new Guid("7ae7e589-f351-4b50-94ad-9575a6c9e6c0"),
                            Code = "TranslateList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Translate List"
                        },
                        new
                        {
                            Id = new Guid("9bb3351d-4b19-487d-901c-44076e68d5f0"),
                            Code = "LogList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "İşlem Kütüğü"
                        },
                        new
                        {
                            Id = new Guid("3b45d807-c146-415d-bc4e-78085410247c"),
                            Code = "LogList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "LogList"
                        },
                        new
                        {
                            Id = new Guid("93da597a-5957-4b5e-af6a-64d4e3c61cca"),
                            Code = "DeleteConfirm",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Emin misiniz?"
                        },
                        new
                        {
                            Id = new Guid("2ce3c738-09b5-4b48-b7f9-c7612600645c"),
                            Code = "DeleteConfirm",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Are you sure?"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<long>("CitizenId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2022, 8, 31, 0, 29, 33, 763, DateTimeKind.Local).AddTicks(4396));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("MobilePhones")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("MobilePhones");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserClaim", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "ClaimId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserGroup", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Entities.Concrete.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("Pid")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
