// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20220903145112_mig4")]
    partial class mig4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Concrete.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Core.Entities.Concrete.GroupClaim", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("GroupId", "ClaimId");

                    b.ToTable("GroupClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Code = "tr-TR",
                            Name = "Türkçe"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Code = "en-US",
                            Name = "English"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Core.Entities.Concrete.MobileLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsSend")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId", "Provider");

                    b.ToTable("MobileLogins");
                });

            modelBuilder.Entity("Core.Entities.Concrete.OperationClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Translate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LangId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Translates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67a91588-f63c-4fe8-a7f1-c83bd5c91b46"),
                            Code = "Login",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Giriş"
                        },
                        new
                        {
                            Id = new Guid("80e3f153-fbb0-49b7-9d93-4051eb53ef4f"),
                            Code = "Email",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "E posta"
                        },
                        new
                        {
                            Id = new Guid("6ffcf7d6-8b05-4a79-81d9-c21f93e6b1b8"),
                            Code = "Password",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Parola"
                        },
                        new
                        {
                            Id = new Guid("a701c71a-2bfe-4b46-899a-0d42901910e6"),
                            Code = "Update",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Güncelle"
                        },
                        new
                        {
                            Id = new Guid("d0d54f9f-4068-41f4-a275-4b8ec51d8c43"),
                            Code = "Delete",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Sil"
                        },
                        new
                        {
                            Id = new Guid("e1533612-c1fc-4d88-8014-eb779387b915"),
                            Code = "UsersGroups",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kullanıcının Grupları"
                        },
                        new
                        {
                            Id = new Guid("013a7ba9-0839-43d8-8622-46e1cc36b06d"),
                            Code = "UsersClaims",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kullanıcının Yetkileri"
                        },
                        new
                        {
                            Id = new Guid("57a5ec1a-a281-4bc0-afee-6f315f7bd1af"),
                            Code = "Create",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yeni"
                        },
                        new
                        {
                            Id = new Guid("4d0fae81-9798-4790-82ee-ddb2aea0b760"),
                            Code = "Users",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kullanıcılar"
                        },
                        new
                        {
                            Id = new Guid("e5820841-bc43-4591-9810-00b2d90381e8"),
                            Code = "Groups",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Gruplar"
                        },
                        new
                        {
                            Id = new Guid("4f0cd345-79c6-402a-a455-deba147e609e"),
                            Code = "Login",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Login"
                        },
                        new
                        {
                            Id = new Guid("982172c2-cc96-4267-8901-3a209c2009cb"),
                            Code = "Email",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Email"
                        },
                        new
                        {
                            Id = new Guid("855cf178-4e53-418c-b40a-7d8bcaddb111"),
                            Code = "Password",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Password"
                        },
                        new
                        {
                            Id = new Guid("0a2facd0-4bc4-4094-aca7-a68559e6d10f"),
                            Code = "Update",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Update"
                        },
                        new
                        {
                            Id = new Guid("e5588741-9469-4758-b57d-051280034679"),
                            Code = "Delete",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Delete"
                        },
                        new
                        {
                            Id = new Guid("ac328a4d-a592-4063-b2af-1c01877bd07d"),
                            Code = "UsersGroups",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "User's Groups"
                        },
                        new
                        {
                            Id = new Guid("91b6712f-d2f6-4911-904c-0bf58f62b571"),
                            Code = "UsersClaims",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "User's Claims"
                        },
                        new
                        {
                            Id = new Guid("233e4da5-a506-416d-b573-00d43bbdcd49"),
                            Code = "Create",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Create"
                        },
                        new
                        {
                            Id = new Guid("adc9d9be-642d-41ee-855a-45537af55af7"),
                            Code = "Users",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Users"
                        },
                        new
                        {
                            Id = new Guid("92be6481-5e61-43ef-92c9-fcfd858dd9f6"),
                            Code = "Groups",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Groups"
                        },
                        new
                        {
                            Id = new Guid("e59b4cf7-700a-4861-a23a-006f778c2896"),
                            Code = "OperationClaim",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Operasyon Yetkileri"
                        },
                        new
                        {
                            Id = new Guid("aca0834b-56ae-4c4a-89a7-7ec8b6fd8bdc"),
                            Code = "OperationClaim",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Operation Claim"
                        },
                        new
                        {
                            Id = new Guid("6987697d-fa42-4a03-a6cb-bff0ae26dcfe"),
                            Code = "Languages",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Diller"
                        },
                        new
                        {
                            Id = new Guid("a10fa7db-d440-4a8d-91fc-e10b0b72b1b9"),
                            Code = "Languages",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Languages"
                        },
                        new
                        {
                            Id = new Guid("80e64156-3296-4f62-9537-6709f9d853f2"),
                            Code = "TranslateWords",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Dil Çevirileri"
                        },
                        new
                        {
                            Id = new Guid("6ea9cf4f-c373-47b3-aee2-d7e1e7a7eb2e"),
                            Code = "TranslateWords",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Translate Words"
                        },
                        new
                        {
                            Id = new Guid("2fe1a353-8415-42e9-a9a5-40a9b2a2fcc3"),
                            Code = "Management",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yönetim"
                        },
                        new
                        {
                            Id = new Guid("395c3f3a-c837-4621-9c35-a63d8bc2e783"),
                            Code = "Management",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Management"
                        },
                        new
                        {
                            Id = new Guid("d584c5c3-bd72-4d0e-98e9-f90fbb742af2"),
                            Code = "AppMenu",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Uygulama"
                        },
                        new
                        {
                            Id = new Guid("4289222e-22b8-43fe-b1bd-2951806ca16a"),
                            Code = "AppMenu",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Application"
                        },
                        new
                        {
                            Id = new Guid("64ea33a5-fa13-4820-9484-e49206009f93"),
                            Code = "Added",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Başarıyla Eklendi."
                        },
                        new
                        {
                            Id = new Guid("534ee674-f5c8-4764-a602-9582c896cca9"),
                            Code = "Added",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Successfully Added."
                        },
                        new
                        {
                            Id = new Guid("bd87bf74-0ea6-443e-88fc-e15fa60bb9b1"),
                            Code = "Updated",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Başarıyla Güncellendi."
                        },
                        new
                        {
                            Id = new Guid("4c310082-5b3f-4cd9-8181-7e24fddb2e11"),
                            Code = "Updated",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Successfully Updated."
                        },
                        new
                        {
                            Id = new Guid("367dd424-398c-47bb-a96e-4f4c13b71459"),
                            Code = "Deleted",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Başarıyla Silindi."
                        },
                        new
                        {
                            Id = new Guid("4c5f7735-c44e-450b-95ef-986af57595e5"),
                            Code = "Deleted",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Successfully Deleted."
                        },
                        new
                        {
                            Id = new Guid("14d885d9-31a0-409f-a6ee-a53f94fb64a3"),
                            Code = "OperationClaimExists",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Bu operasyon izni zaten mevcut."
                        },
                        new
                        {
                            Id = new Guid("5dbaaeb8-ba0b-4022-9261-ec45789b4789"),
                            Code = "OperationClaimExists",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "This operation permit already exists."
                        },
                        new
                        {
                            Id = new Guid("2f9e9eb0-b89f-4050-8e9f-4b540ffb9ea8"),
                            Code = "StringLengthMustBeGreaterThanThree",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Lütfen En Az 3 Karakterden Oluşan Bir İfade Girin."
                        },
                        new
                        {
                            Id = new Guid("10e85791-f77e-4e68-af93-454a3418ed15"),
                            Code = "StringLengthMustBeGreaterThanThree",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Please Enter A Phrase Of At Least 3 Characters."
                        },
                        new
                        {
                            Id = new Guid("7a1329a6-fc6b-49d2-9030-27fb58cc6da1"),
                            Code = "CouldNotBeVerifyCid",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kimlik No Doğrulanamadı."
                        },
                        new
                        {
                            Id = new Guid("0b0589a0-f4cd-404a-b757-c68f0724319e"),
                            Code = "CouldNotBeVerifyCid",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Could not be verify Citizen Id"
                        },
                        new
                        {
                            Id = new Guid("35094886-a959-4aa4-ab6f-ba278fd3e4c2"),
                            Code = "VerifyCid",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kimlik No Doğrulandı."
                        },
                        new
                        {
                            Id = new Guid("2dbf2550-3925-4872-8c46-4ba51239a735"),
                            Code = "VerifyCid",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Verify Citizen Id"
                        },
                        new
                        {
                            Id = new Guid("6c166cbf-25cb-4b11-a0b5-156bef19af57"),
                            Code = "AuthorizationsDenied",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yetkiniz olmayan bir alana girmeye çalıştığınız tespit edildi."
                        },
                        new
                        {
                            Id = new Guid("afb00f47-ca22-4ddf-a1dc-9311ed68cbf3"),
                            Code = "AuthorizationsDenied",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "It has been detected that you are trying to enter an area that you do not have authorization."
                        },
                        new
                        {
                            Id = new Guid("ab053920-92d7-4f33-b7a5-20968396c414"),
                            Code = "UserNotFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kimlik Bilgileri Doğrulanamadı. Lütfen Yeni Kayıt Ekranını kullanın."
                        },
                        new
                        {
                            Id = new Guid("337f5398-c1fd-49b2-a7db-7855b4098ddb"),
                            Code = "UserNotFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Credentials Could Not Verify. Please use the New Registration Screen."
                        },
                        new
                        {
                            Id = new Guid("44ab149a-c4ea-4a64-a027-e8fb98b74fd5"),
                            Code = "PasswordError",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kimlik Bilgileri Doğrulanamadı, Kullanıcı adı ve/veya parola hatalı."
                        },
                        new
                        {
                            Id = new Guid("3641fdb9-1328-472b-b860-be9c9068a529"),
                            Code = "PasswordError",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Credentials Failed to Authenticate, Username and / or password incorrect."
                        },
                        new
                        {
                            Id = new Guid("46c0e8f9-4e22-4d40-9f1b-18ef9b5878f1"),
                            Code = "SuccessfulLogin",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Sisteme giriş başarılı."
                        },
                        new
                        {
                            Id = new Guid("ea55f696-d610-4f8d-9a35-f129a98e08a6"),
                            Code = "SuccessfulLogin",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Login to the system is successful."
                        },
                        new
                        {
                            Id = new Guid("0f888893-eeac-4e1a-bb1e-060e389de08a"),
                            Code = "SendMobileCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Lütfen Size SMS Olarak Gönderilen Kodu Girin!"
                        },
                        new
                        {
                            Id = new Guid("92afe69e-8bc0-45d6-8f56-b4a78f65ac5f"),
                            Code = "SendMobileCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Please Enter The Code Sent To You By SMS!"
                        },
                        new
                        {
                            Id = new Guid("25ad6665-690b-4dfb-b84f-01c273c3d1fe"),
                            Code = "NameAlreadyExist",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Oluşturmaya Çalıştığınız Nesne Zaten Var."
                        },
                        new
                        {
                            Id = new Guid("68dc4b37-71b5-405a-ba44-21276be04ce1"),
                            Code = "NameAlreadyExist",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "The Object You Are Trying To Create Already Exists."
                        },
                        new
                        {
                            Id = new Guid("b18c2e27-1075-4ecb-a88e-07975b1d19a8"),
                            Code = "WrongCID",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Vatandaşlık No Sistemimizde Bulunamadı. Lütfen Yeni Kayıt Oluşturun!"
                        },
                        new
                        {
                            Id = new Guid("38957c5a-53f4-417c-a860-f56b814fd256"),
                            Code = "WrongCID",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Citizenship Number Not Found In Our System. Please Create New Registration!"
                        },
                        new
                        {
                            Id = new Guid("dd7dadc2-a942-4968-b170-fc0ce9a032de"),
                            Code = "CID",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Vatandaşlık No"
                        },
                        new
                        {
                            Id = new Guid("89983521-3755-46d0-bcec-2cf7605815c0"),
                            Code = "CID",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Citizenship Number"
                        },
                        new
                        {
                            Id = new Guid("69d1041f-92e4-4d2d-a50a-2b158ed82cf5"),
                            Code = "PasswordEmpty",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Parola boş olamaz!"
                        },
                        new
                        {
                            Id = new Guid("ac4d9f4b-c2b4-4377-8b4c-9ae17816a0fd"),
                            Code = "PasswordEmpty",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Password can not be empty!"
                        },
                        new
                        {
                            Id = new Guid("f6afdb72-9f41-4cbb-8f79-64abc1640924"),
                            Code = "PasswordLength",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Minimum 8 Karakter Uzunluğunda Olmalıdır!"
                        },
                        new
                        {
                            Id = new Guid("51984db9-958f-4a11-842d-acd106976b15"),
                            Code = "PasswordLength",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Must be at least 8 characters long! "
                        },
                        new
                        {
                            Id = new Guid("427f092b-4498-4f3a-b0e4-6995562d57fa"),
                            Code = "PasswordUppercaseLetter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "En Az 1 Büyük Harf İçermelidir!"
                        },
                        new
                        {
                            Id = new Guid("6c18b231-10bd-4823-b2a3-e6994eb299a7"),
                            Code = "PasswordUppercaseLetter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Must Contain At Least 1 Capital Letter!"
                        },
                        new
                        {
                            Id = new Guid("e4f6f0ba-5f0a-4368-b0eb-e2a820a3b86b"),
                            Code = "PasswordLowercaseLetter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "En Az 1 Küçük Harf İçermelidir!"
                        },
                        new
                        {
                            Id = new Guid("05e45e43-7c8a-428a-a2bc-b5dab2fd35c1"),
                            Code = "PasswordLowercaseLetter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Must Contain At Least 1 Lowercase Letter!"
                        },
                        new
                        {
                            Id = new Guid("baefbda2-234d-4001-a1ff-67073a782309"),
                            Code = "PasswordDigit",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "En Az 1 Rakam İçermelidir!"
                        },
                        new
                        {
                            Id = new Guid("3543189f-b9cb-4eb0-b60c-46f158ac52d7"),
                            Code = "PasswordDigit",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "It Must Contain At Least 1 Digit!"
                        },
                        new
                        {
                            Id = new Guid("3e3c9085-9375-4362-b0ef-e8145a6c3a50"),
                            Code = "PasswordSpecialCharacter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "En Az 1 Simge İçermelidir!"
                        },
                        new
                        {
                            Id = new Guid("e9db04b9-6042-4452-a67a-fee3f3920bb2"),
                            Code = "PasswordSpecialCharacter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Must Contain At Least 1 Symbol!"
                        },
                        new
                        {
                            Id = new Guid("477bf374-e326-4100-a99b-4812308ff56e"),
                            Code = "SendPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yeni Parolanız E-Posta Adresinize Gönderildi."
                        },
                        new
                        {
                            Id = new Guid("bcb84637-00d2-4d73-8c00-fb923bb9e4a3"),
                            Code = "SendPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Your new password has been sent to your e-mail address."
                        },
                        new
                        {
                            Id = new Guid("a1e9797e-c489-4db5-ac3a-ba896857379d"),
                            Code = "InvalidCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Geçersiz Bir Kod Girdiniz!"
                        },
                        new
                        {
                            Id = new Guid("b9bf3e22-8f6c-44cf-a60a-69f5c7083ada"),
                            Code = "InvalidCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "You Entered An Invalid Code!"
                        },
                        new
                        {
                            Id = new Guid("d6b7a2f7-ffcf-4306-b39d-06d02c68275d"),
                            Code = "SmsServiceNotFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "SMS Servisine Ulaşılamıyor."
                        },
                        new
                        {
                            Id = new Guid("2b1bd578-8973-4005-b63d-6b7361b57ac7"),
                            Code = "SmsServiceNotFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Unable to Reach SMS Service."
                        },
                        new
                        {
                            Id = new Guid("c21cbbb7-b546-446e-8fd1-95f8918d1111"),
                            Code = "TrueButCellPhone",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Bilgiler doğru. Cep telefonu gerekiyor."
                        },
                        new
                        {
                            Id = new Guid("034364d2-a01f-4302-a7b5-e951d5950ff8"),
                            Code = "TrueButCellPhone",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "The information is correct. Cell phone is required."
                        },
                        new
                        {
                            Id = new Guid("ea312dd9-92ba-4ace-b303-a4622db40137"),
                            Code = "TokenProviderException",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Token Provider boş olamaz!"
                        },
                        new
                        {
                            Id = new Guid("fb57c7b8-ae9f-4bb3-9f00-ca9fb7538058"),
                            Code = "TokenProviderException",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Token Provider cannot be empty!"
                        },
                        new
                        {
                            Id = new Guid("e39b570a-d485-4408-a79e-c41801bd0c61"),
                            Code = "Unknown",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Bilinmiyor!"
                        },
                        new
                        {
                            Id = new Guid("5c57297f-585d-41e6-bb1a-670a6b523287"),
                            Code = "Unknown",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Unknown!"
                        },
                        new
                        {
                            Id = new Guid("726e00cc-d6eb-4f88-9ba6-43ad47d0a6b6"),
                            Code = "NewPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yeni Parola:"
                        },
                        new
                        {
                            Id = new Guid("5bb4482e-ec50-4cb7-950f-49ead7d4ce29"),
                            Code = "NewPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "New Password:"
                        },
                        new
                        {
                            Id = new Guid("3c10378e-a38f-4a84-ae8c-eacb94e7fcdc"),
                            Code = "ChangePassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Parola Değiştir"
                        },
                        new
                        {
                            Id = new Guid("84b68c50-ded4-42da-a03b-b4bbd2c86bad"),
                            Code = "ChangePassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Change Password"
                        },
                        new
                        {
                            Id = new Guid("7425e542-24c1-4f16-b034-76e327fbe817"),
                            Code = "Save",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kaydet"
                        },
                        new
                        {
                            Id = new Guid("ad09e4fe-ed0e-42fb-a9ab-7f8841211a4d"),
                            Code = "Save",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Save"
                        },
                        new
                        {
                            Id = new Guid("1f498a9f-d573-419d-8c05-b25fa38916d4"),
                            Code = "GroupName",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Grup Adı"
                        },
                        new
                        {
                            Id = new Guid("d65073c1-1f8c-4d0d-8e98-00ed825fc530"),
                            Code = "GroupName",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Group Name"
                        },
                        new
                        {
                            Id = new Guid("29caa88a-7f63-4f6e-a0f0-19891ba8705a"),
                            Code = "FullName",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Tam Adı"
                        },
                        new
                        {
                            Id = new Guid("6df7210a-a96a-49b1-88ee-ab7c677190a5"),
                            Code = "FullName",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Full Name"
                        },
                        new
                        {
                            Id = new Guid("b988a369-d413-4da6-a738-34c09a999616"),
                            Code = "Address",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Adres"
                        },
                        new
                        {
                            Id = new Guid("4464ac2e-2e3c-4717-b272-2a0c1be011fa"),
                            Code = "Address",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Address"
                        },
                        new
                        {
                            Id = new Guid("22956e88-5aeb-4c45-b9f9-986dcd3e4bf7"),
                            Code = "Notes",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Notlar"
                        },
                        new
                        {
                            Id = new Guid("78212d3e-cb08-4432-b616-6b33f73f10e3"),
                            Code = "Notes",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Notes"
                        },
                        new
                        {
                            Id = new Guid("c0d3fc59-07e8-4a1c-9da9-c21c4096bb09"),
                            Code = "ConfirmPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Parolayı Doğrula"
                        },
                        new
                        {
                            Id = new Guid("d2997564-39d1-4fcf-b76a-a4d341283acb"),
                            Code = "ConfirmPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Confirm Password"
                        },
                        new
                        {
                            Id = new Guid("d5d72c4c-d7d0-4d55-8ad3-6a7130945a77"),
                            Code = "Code",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kod"
                        },
                        new
                        {
                            Id = new Guid("45e55b4e-f6f7-4d59-9265-d52356e010ae"),
                            Code = "Code",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Code"
                        },
                        new
                        {
                            Id = new Guid("bfc8c8b4-4ae6-4f27-8307-8671434d312e"),
                            Code = "Alias",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Görünen Ad"
                        },
                        new
                        {
                            Id = new Guid("33bf6e9a-827e-40d6-bf91-69287a614131"),
                            Code = "Alias",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Alias"
                        },
                        new
                        {
                            Id = new Guid("d1bc350e-a6c4-417f-bf43-0b9054327e4c"),
                            Code = "Description",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Açıklama"
                        },
                        new
                        {
                            Id = new Guid("b5e793bd-8fdf-4cb7-b38a-9f7443b5af9a"),
                            Code = "Description",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Description"
                        },
                        new
                        {
                            Id = new Guid("71eee4d6-6c30-4b9d-a808-1e544aa2d38f"),
                            Code = "Value",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Değer"
                        },
                        new
                        {
                            Id = new Guid("f6aa55a6-b153-493a-967d-1503e659cae1"),
                            Code = "Value",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Value"
                        },
                        new
                        {
                            Id = new Guid("d9b6db3d-cbac-4778-a0c6-5b70c71f656e"),
                            Code = "LangCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Dil Kodu"
                        },
                        new
                        {
                            Id = new Guid("718e6779-c256-462b-a09b-85a836fe8237"),
                            Code = "LangCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Lang Code"
                        },
                        new
                        {
                            Id = new Guid("7daed0fc-d389-4f3d-8fea-c932d0059352"),
                            Code = "Name",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Adı"
                        },
                        new
                        {
                            Id = new Guid("362eeb42-78d6-4521-85b9-3dfa266cc508"),
                            Code = "Name",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Name"
                        },
                        new
                        {
                            Id = new Guid("f995bc49-c7d9-4ba5-a17f-d81896cbbe17"),
                            Code = "MobilePhones",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Cep Telefonu"
                        },
                        new
                        {
                            Id = new Guid("1bf7c9c9-f246-4b1b-9cd9-c6a9e1531d48"),
                            Code = "MobilePhones",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Mobile Phone"
                        },
                        new
                        {
                            Id = new Guid("c96aecb2-8d95-4194-a935-c29fc342a6a6"),
                            Code = "NoRecordsFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kayıt Bulunamadı"
                        },
                        new
                        {
                            Id = new Guid("914f962b-ded6-4b64-ba01-514fb4b7db84"),
                            Code = "NoRecordsFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "No Records Found"
                        },
                        new
                        {
                            Id = new Guid("4e2ddcee-9598-4958-8308-5187dc9f4e9c"),
                            Code = "Required",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Bu alan zorunludur!"
                        },
                        new
                        {
                            Id = new Guid("53fc4e1b-5de8-4d48-b81b-1f2458829537"),
                            Code = "Required",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "This field is required!"
                        },
                        new
                        {
                            Id = new Guid("33d9bedc-ba44-4005-a337-98655be7c75c"),
                            Code = "Permissions",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Permissions"
                        },
                        new
                        {
                            Id = new Guid("70236ef5-e6da-405e-8714-2471c039dff8"),
                            Code = "Permissions",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "İzinler"
                        },
                        new
                        {
                            Id = new Guid("42601b4c-0d3b-4e0a-85f5-a6e02589a60a"),
                            Code = "GroupList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Grup Listesi"
                        },
                        new
                        {
                            Id = new Guid("6ac74305-bcf9-4af7-8121-7ced8538c8dc"),
                            Code = "GroupList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Group List"
                        },
                        new
                        {
                            Id = new Guid("66b3c7e4-dae1-4e10-b387-774cad442870"),
                            Code = "GrupPermissions",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Grup Yetkileri"
                        },
                        new
                        {
                            Id = new Guid("4f7a681e-0d5d-4c5b-9a9e-e85f7df65961"),
                            Code = "GrupPermissions",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Grup Permissions"
                        },
                        new
                        {
                            Id = new Guid("6428e509-d82c-4683-9148-94e5a398a9d1"),
                            Code = "Add",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Ekle"
                        },
                        new
                        {
                            Id = new Guid("e7d57b1b-f533-42a8-85ae-5200682177b3"),
                            Code = "Add",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Add"
                        },
                        new
                        {
                            Id = new Guid("50d8bfab-33b6-46ef-8168-39a6f8743db3"),
                            Code = "UserList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kullanıcı Listesi"
                        },
                        new
                        {
                            Id = new Guid("c3da3b2b-1363-48de-b276-b1708ab42695"),
                            Code = "UserList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "User List"
                        },
                        new
                        {
                            Id = new Guid("84db0902-a581-4c97-bb7e-b64cec24b66d"),
                            Code = "OperationClaimList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yetki Listesi"
                        },
                        new
                        {
                            Id = new Guid("816b1c16-2a00-4542-8cd0-3de8322d6309"),
                            Code = "OperationClaimList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "OperationClaim List"
                        },
                        new
                        {
                            Id = new Guid("74c6b1b0-f295-4dd8-a06a-4f291464c2f9"),
                            Code = "LanguageList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Dil Listesi"
                        },
                        new
                        {
                            Id = new Guid("bc3db746-ab46-4368-89cc-c2e7da2800c5"),
                            Code = "LanguageList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Language List"
                        },
                        new
                        {
                            Id = new Guid("d3b0ea13-8fd0-4bcd-97b6-acf95ef5a361"),
                            Code = "TranslateList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Dil Çeviri Listesi"
                        },
                        new
                        {
                            Id = new Guid("98a94961-439f-44f4-bf23-6e518655393b"),
                            Code = "TranslateList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Translate List"
                        },
                        new
                        {
                            Id = new Guid("e195d01f-0c4c-4247-b551-fb5b41c08725"),
                            Code = "LogList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "İşlem Kütüğü"
                        },
                        new
                        {
                            Id = new Guid("1e704e78-8dcb-4eb4-bb26-10d4b9f76d49"),
                            Code = "LogList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "LogList"
                        },
                        new
                        {
                            Id = new Guid("4e45438f-2fd3-4f71-b11c-de07ea79437a"),
                            Code = "DeleteConfirm",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Emin misiniz?"
                        },
                        new
                        {
                            Id = new Guid("0e407368-440e-48dc-8072-e5aff375f191"),
                            Code = "DeleteConfirm",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Are you sure?"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<long>("CitizenId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 9, 3, 17, 51, 11, 917, DateTimeKind.Local).AddTicks(8950));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("MobilePhones")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("MobilePhones");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id", "UserId", "ClaimId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserGroup", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Entities.Concrete.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("Pid")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
