// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DataAccess.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20220830213801_mig3")]
    partial class mig3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Core.Entities.Concrete.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Core.Entities.Concrete.GroupClaim", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupId", "ClaimId");

                    b.ToTable("GroupClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Code = "tr-TR",
                            Name = "Türkçe"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Code = "en-US",
                            Name = "English"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Core.Entities.Concrete.MobileLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsSend")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId", "Provider");

                    b.ToTable("MobileLogins");
                });

            modelBuilder.Entity("Core.Entities.Concrete.OperationClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Translate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LangId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Translates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("be3f33b3-6c9f-483c-92ec-ee10555d0111"),
                            Code = "Login",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Giriş"
                        },
                        new
                        {
                            Id = new Guid("4ebb9247-dbba-4d91-b581-d4f34637416a"),
                            Code = "Email",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "E posta"
                        },
                        new
                        {
                            Id = new Guid("8d175127-5f09-49f8-9aac-166e333dd3c1"),
                            Code = "Password",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Parola"
                        },
                        new
                        {
                            Id = new Guid("d3f9ba74-4d52-4f44-baa5-403f0b774fb5"),
                            Code = "Update",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Güncelle"
                        },
                        new
                        {
                            Id = new Guid("2a4c2ab9-9033-4196-bbd9-cbbdd38df365"),
                            Code = "Delete",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Sil"
                        },
                        new
                        {
                            Id = new Guid("f315b994-67c6-44cb-b064-6c931d2d93cf"),
                            Code = "UsersGroups",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kullanıcının Grupları"
                        },
                        new
                        {
                            Id = new Guid("ad7b867c-a8cc-4950-b35e-356e4f712ecd"),
                            Code = "UsersClaims",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kullanıcının Yetkileri"
                        },
                        new
                        {
                            Id = new Guid("5112ac1e-cb1a-409a-91f3-97c8735ed1eb"),
                            Code = "Create",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yeni"
                        },
                        new
                        {
                            Id = new Guid("c8d34e9a-200b-4b47-b397-eda352d12460"),
                            Code = "Users",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kullanıcılar"
                        },
                        new
                        {
                            Id = new Guid("38bae803-b3c5-4085-9658-0b39bd53a3dd"),
                            Code = "Groups",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Gruplar"
                        },
                        new
                        {
                            Id = new Guid("c096cc86-a172-4e6c-a175-b0d50c54c2cc"),
                            Code = "Login",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Login"
                        },
                        new
                        {
                            Id = new Guid("24c87c97-4d81-48f8-b2e7-c54dd5c1c8b6"),
                            Code = "Email",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Email"
                        },
                        new
                        {
                            Id = new Guid("4804c8ec-a815-4a83-a528-c5bddb27be79"),
                            Code = "Password",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Password"
                        },
                        new
                        {
                            Id = new Guid("4a5fb2ab-7897-42e3-b0d1-03f4682c7245"),
                            Code = "Update",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Update"
                        },
                        new
                        {
                            Id = new Guid("242444d8-0709-4086-b7b2-6aa9b3604e6a"),
                            Code = "Delete",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Delete"
                        },
                        new
                        {
                            Id = new Guid("c151e878-d7dc-4be6-a7e2-09abe1ca8e12"),
                            Code = "UsersGroups",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "User's Groups"
                        },
                        new
                        {
                            Id = new Guid("c84ed780-4b2c-44f0-a74a-71135ef1ced1"),
                            Code = "UsersClaims",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "User's Claims"
                        },
                        new
                        {
                            Id = new Guid("928e360f-15ec-4d5d-a57c-5d6cf92417d6"),
                            Code = "Create",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Create"
                        },
                        new
                        {
                            Id = new Guid("f78efd7c-9df1-41f8-9a9b-5172b4557e39"),
                            Code = "Users",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Users"
                        },
                        new
                        {
                            Id = new Guid("3f80afb7-791c-494b-8ef7-0f13e12e3e92"),
                            Code = "Groups",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Groups"
                        },
                        new
                        {
                            Id = new Guid("b70a5dfa-4707-42aa-8fd6-67323fa2c69c"),
                            Code = "OperationClaim",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Operasyon Yetkileri"
                        },
                        new
                        {
                            Id = new Guid("8b3a2f74-817d-4996-8ce7-0166805ed49f"),
                            Code = "OperationClaim",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Operation Claim"
                        },
                        new
                        {
                            Id = new Guid("e8018f8a-667d-46b7-9c57-3f840a4337a6"),
                            Code = "Languages",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Diller"
                        },
                        new
                        {
                            Id = new Guid("5be7ee03-24eb-47fe-84d4-68307f195594"),
                            Code = "Languages",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Languages"
                        },
                        new
                        {
                            Id = new Guid("e4f973a2-e586-421e-afaf-b183ec193e55"),
                            Code = "TranslateWords",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Dil Çevirileri"
                        },
                        new
                        {
                            Id = new Guid("87dcabf9-6870-4a32-a09e-144527463db9"),
                            Code = "TranslateWords",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Translate Words"
                        },
                        new
                        {
                            Id = new Guid("c03bec61-7b52-49f3-8501-640fe9b64574"),
                            Code = "Management",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yönetim"
                        },
                        new
                        {
                            Id = new Guid("3140658e-f9fa-48f8-a62e-bd133e1b7338"),
                            Code = "Management",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Management"
                        },
                        new
                        {
                            Id = new Guid("9b0da6ea-034f-4c3e-bdf2-996303bb538d"),
                            Code = "AppMenu",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Uygulama"
                        },
                        new
                        {
                            Id = new Guid("f0bb88f2-903d-4e20-866a-6b441d555f2b"),
                            Code = "AppMenu",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Application"
                        },
                        new
                        {
                            Id = new Guid("b71c815c-96af-4681-878a-e54a725c8585"),
                            Code = "Added",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Başarıyla Eklendi."
                        },
                        new
                        {
                            Id = new Guid("83d1bcd5-bc6f-4082-8731-a2c65ffa9b73"),
                            Code = "Added",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Successfully Added."
                        },
                        new
                        {
                            Id = new Guid("c4e6f9a1-8c92-478d-8b18-32cde96c783d"),
                            Code = "Updated",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Başarıyla Güncellendi."
                        },
                        new
                        {
                            Id = new Guid("410be70b-b0fd-49b0-8540-8fd3189055f8"),
                            Code = "Updated",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Successfully Updated."
                        },
                        new
                        {
                            Id = new Guid("732bd376-96e0-41a1-85e8-551dd5a62b3c"),
                            Code = "Deleted",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Başarıyla Silindi."
                        },
                        new
                        {
                            Id = new Guid("fbf82790-9e79-4797-a199-159afc9ea980"),
                            Code = "Deleted",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Successfully Deleted."
                        },
                        new
                        {
                            Id = new Guid("fed9b57c-6931-4ac7-9f24-dd33746c61d6"),
                            Code = "OperationClaimExists",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Bu operasyon izni zaten mevcut."
                        },
                        new
                        {
                            Id = new Guid("68e50cd6-1e27-44ec-8124-ade1aa0d8dcd"),
                            Code = "OperationClaimExists",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "This operation permit already exists."
                        },
                        new
                        {
                            Id = new Guid("4b2a2f97-ad27-4dec-8756-7d362beda395"),
                            Code = "StringLengthMustBeGreaterThanThree",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Lütfen En Az 3 Karakterden Oluşan Bir İfade Girin."
                        },
                        new
                        {
                            Id = new Guid("bf83a360-5b65-4597-b414-c35f8d37afc1"),
                            Code = "StringLengthMustBeGreaterThanThree",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Please Enter A Phrase Of At Least 3 Characters."
                        },
                        new
                        {
                            Id = new Guid("66cba36d-87bf-43e8-b879-0e468b305c89"),
                            Code = "CouldNotBeVerifyCid",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kimlik No Doğrulanamadı."
                        },
                        new
                        {
                            Id = new Guid("306241ba-3f50-4745-be38-595356cc1160"),
                            Code = "CouldNotBeVerifyCid",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Could not be verify Citizen Id"
                        },
                        new
                        {
                            Id = new Guid("4325dc8f-cb78-4296-8be2-f9b81dac6b3d"),
                            Code = "VerifyCid",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kimlik No Doğrulandı."
                        },
                        new
                        {
                            Id = new Guid("0821831a-6465-440f-ade1-55cb408018cc"),
                            Code = "VerifyCid",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Verify Citizen Id"
                        },
                        new
                        {
                            Id = new Guid("ea01ab9a-7a0c-44b6-85cd-feb9a8cbdb94"),
                            Code = "AuthorizationsDenied",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yetkiniz olmayan bir alana girmeye çalıştığınız tespit edildi."
                        },
                        new
                        {
                            Id = new Guid("acdb0ae8-901f-4a9d-99eb-2566fda69e56"),
                            Code = "AuthorizationsDenied",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "It has been detected that you are trying to enter an area that you do not have authorization."
                        },
                        new
                        {
                            Id = new Guid("bf77e8e2-7657-43f3-af25-89b0fc8522b1"),
                            Code = "UserNotFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kimlik Bilgileri Doğrulanamadı. Lütfen Yeni Kayıt Ekranını kullanın."
                        },
                        new
                        {
                            Id = new Guid("52d81953-5cc7-45f0-bd23-b010a18dc163"),
                            Code = "UserNotFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Credentials Could Not Verify. Please use the New Registration Screen."
                        },
                        new
                        {
                            Id = new Guid("acb327b1-360b-453b-8413-67dd5b94b79d"),
                            Code = "PasswordError",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kimlik Bilgileri Doğrulanamadı, Kullanıcı adı ve/veya parola hatalı."
                        },
                        new
                        {
                            Id = new Guid("b012a2ce-60e8-49f0-b420-f215b460c17a"),
                            Code = "PasswordError",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Credentials Failed to Authenticate, Username and / or password incorrect."
                        },
                        new
                        {
                            Id = new Guid("8a1c7d42-b929-443e-8157-f801f787a592"),
                            Code = "SuccessfulLogin",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Sisteme giriş başarılı."
                        },
                        new
                        {
                            Id = new Guid("fd4e82b9-d0a4-437a-9fb8-18b7f077cb33"),
                            Code = "SuccessfulLogin",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Login to the system is successful."
                        },
                        new
                        {
                            Id = new Guid("70f44a94-85e4-403e-adde-8c21b10f8c4c"),
                            Code = "SendMobileCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Lütfen Size SMS Olarak Gönderilen Kodu Girin!"
                        },
                        new
                        {
                            Id = new Guid("30ccab6b-b1f0-4a04-9cc9-80e62e01334c"),
                            Code = "SendMobileCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Please Enter The Code Sent To You By SMS!"
                        },
                        new
                        {
                            Id = new Guid("1da2d933-e5ef-42a8-bba0-c8c8346a1437"),
                            Code = "NameAlreadyExist",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Oluşturmaya Çalıştığınız Nesne Zaten Var."
                        },
                        new
                        {
                            Id = new Guid("f76b2aa2-3979-444d-b2fe-dca218e750ba"),
                            Code = "NameAlreadyExist",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "The Object You Are Trying To Create Already Exists."
                        },
                        new
                        {
                            Id = new Guid("2e762770-1a0d-47ce-a403-7f469afa852b"),
                            Code = "WrongCID",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Vatandaşlık No Sistemimizde Bulunamadı. Lütfen Yeni Kayıt Oluşturun!"
                        },
                        new
                        {
                            Id = new Guid("ee682d8e-cb1e-469a-8107-639e8f8b56ab"),
                            Code = "WrongCID",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Citizenship Number Not Found In Our System. Please Create New Registration!"
                        },
                        new
                        {
                            Id = new Guid("a322344c-21e1-4649-bf25-d8e1f613bf87"),
                            Code = "CID",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Vatandaşlık No"
                        },
                        new
                        {
                            Id = new Guid("723d3920-7dab-4c76-81ab-485169554b76"),
                            Code = "CID",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Citizenship Number"
                        },
                        new
                        {
                            Id = new Guid("f946d22c-17e9-4ec8-8d2e-f6d82f91f041"),
                            Code = "PasswordEmpty",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Parola boş olamaz!"
                        },
                        new
                        {
                            Id = new Guid("e75a07b3-fd42-4448-ac8f-2a9aae23a6e6"),
                            Code = "PasswordEmpty",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Password can not be empty!"
                        },
                        new
                        {
                            Id = new Guid("61479139-ad9e-4fc7-ba8c-062aaed11c3b"),
                            Code = "PasswordLength",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Minimum 8 Karakter Uzunluğunda Olmalıdır!"
                        },
                        new
                        {
                            Id = new Guid("6da7a474-ef83-48aa-bcdb-bbc00f7f5502"),
                            Code = "PasswordLength",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Must be at least 8 characters long! "
                        },
                        new
                        {
                            Id = new Guid("17ee2827-cb55-4013-8a98-cd16b0b85e33"),
                            Code = "PasswordUppercaseLetter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "En Az 1 Büyük Harf İçermelidir!"
                        },
                        new
                        {
                            Id = new Guid("e6a23e57-34f7-4b23-98ef-039f865a0fcf"),
                            Code = "PasswordUppercaseLetter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Must Contain At Least 1 Capital Letter!"
                        },
                        new
                        {
                            Id = new Guid("fe93699d-e78c-46b1-ba18-24616c4e538d"),
                            Code = "PasswordLowercaseLetter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "En Az 1 Küçük Harf İçermelidir!"
                        },
                        new
                        {
                            Id = new Guid("175ab9ab-040d-4f21-b6d4-e028c7d635d7"),
                            Code = "PasswordLowercaseLetter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Must Contain At Least 1 Lowercase Letter!"
                        },
                        new
                        {
                            Id = new Guid("eb86185f-b4dc-4512-8011-68f666aeb07e"),
                            Code = "PasswordDigit",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "En Az 1 Rakam İçermelidir!"
                        },
                        new
                        {
                            Id = new Guid("0d2dea8b-b841-44a2-bf82-854ed0924f56"),
                            Code = "PasswordDigit",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "It Must Contain At Least 1 Digit!"
                        },
                        new
                        {
                            Id = new Guid("13a3a01e-2c9e-4330-93b6-22e62325920b"),
                            Code = "PasswordSpecialCharacter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "En Az 1 Simge İçermelidir!"
                        },
                        new
                        {
                            Id = new Guid("18a87c90-3e72-4402-b6a5-fcf1ec137b03"),
                            Code = "PasswordSpecialCharacter",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Must Contain At Least 1 Symbol!"
                        },
                        new
                        {
                            Id = new Guid("dbdd5473-104c-4fab-944b-baf43de627d1"),
                            Code = "SendPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yeni Parolanız E-Posta Adresinize Gönderildi."
                        },
                        new
                        {
                            Id = new Guid("ae161f8e-0b78-4c19-92b0-c8915e051d84"),
                            Code = "SendPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Your new password has been sent to your e-mail address."
                        },
                        new
                        {
                            Id = new Guid("2485d259-f6af-4c3d-ab15-73f9f109e4cd"),
                            Code = "InvalidCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Geçersiz Bir Kod Girdiniz!"
                        },
                        new
                        {
                            Id = new Guid("3eca76db-4dc4-4e56-9a57-4e2e3771e2d9"),
                            Code = "InvalidCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "You Entered An Invalid Code!"
                        },
                        new
                        {
                            Id = new Guid("a616b8f5-f300-455a-80c6-2a59baefd713"),
                            Code = "SmsServiceNotFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "SMS Servisine Ulaşılamıyor."
                        },
                        new
                        {
                            Id = new Guid("d0b2034c-42ae-41d6-b76b-25d5e97634a8"),
                            Code = "SmsServiceNotFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Unable to Reach SMS Service."
                        },
                        new
                        {
                            Id = new Guid("1dd638d2-33ec-424e-b1c9-5fc0359e721a"),
                            Code = "TrueButCellPhone",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Bilgiler doğru. Cep telefonu gerekiyor."
                        },
                        new
                        {
                            Id = new Guid("79f815dd-77ac-4e4b-b5a2-3e9e414fa582"),
                            Code = "TrueButCellPhone",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "The information is correct. Cell phone is required."
                        },
                        new
                        {
                            Id = new Guid("0d8e183d-c3d6-4d95-8e4c-94b0c0640f7b"),
                            Code = "TokenProviderException",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Token Provider boş olamaz!"
                        },
                        new
                        {
                            Id = new Guid("9c917898-9a44-4589-b44e-9509617a4e4a"),
                            Code = "TokenProviderException",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Token Provider cannot be empty!"
                        },
                        new
                        {
                            Id = new Guid("ac7cb685-8b9d-4355-8354-c15019546c61"),
                            Code = "Unknown",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Bilinmiyor!"
                        },
                        new
                        {
                            Id = new Guid("a60a627d-f714-4347-b399-227f4188f11d"),
                            Code = "Unknown",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Unknown!"
                        },
                        new
                        {
                            Id = new Guid("b5987a6c-6583-46af-8edc-5e541283bfe0"),
                            Code = "NewPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yeni Parola:"
                        },
                        new
                        {
                            Id = new Guid("b95900c4-6aba-4932-81a2-dc2ac9ad2075"),
                            Code = "NewPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "New Password:"
                        },
                        new
                        {
                            Id = new Guid("ce009b40-146b-4378-99b7-19153a024346"),
                            Code = "ChangePassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Parola Değiştir"
                        },
                        new
                        {
                            Id = new Guid("e30886fc-2145-4645-87c9-8dc350b18cc2"),
                            Code = "ChangePassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Change Password"
                        },
                        new
                        {
                            Id = new Guid("e2cb61a9-c070-48e6-90dc-d84b117fe5dd"),
                            Code = "Save",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kaydet"
                        },
                        new
                        {
                            Id = new Guid("bfd88872-cbc6-4f05-9d74-06bca2f3ed3d"),
                            Code = "Save",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Save"
                        },
                        new
                        {
                            Id = new Guid("71e82a4f-427d-4d60-a65c-a04d8faa1e09"),
                            Code = "GroupName",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Grup Adı"
                        },
                        new
                        {
                            Id = new Guid("8f41ccfb-e5c6-4233-b5e4-3cfde0eb696e"),
                            Code = "GroupName",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Group Name"
                        },
                        new
                        {
                            Id = new Guid("b96944e0-cef0-420b-86bc-7863c9ae9434"),
                            Code = "FullName",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Tam Adı"
                        },
                        new
                        {
                            Id = new Guid("746963b5-4980-4700-86bc-d319a0e5c967"),
                            Code = "FullName",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Full Name"
                        },
                        new
                        {
                            Id = new Guid("bf603a6d-d225-4156-8f33-61a00e0af3cc"),
                            Code = "Address",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Adres"
                        },
                        new
                        {
                            Id = new Guid("70f9d16e-f0fe-434a-a222-8f114582165e"),
                            Code = "Address",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Address"
                        },
                        new
                        {
                            Id = new Guid("703bb537-fa7f-44a3-aeda-3ded566e44c6"),
                            Code = "Notes",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Notlar"
                        },
                        new
                        {
                            Id = new Guid("c64afa03-92dd-4c1b-a925-ac94ba7efba7"),
                            Code = "Notes",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Notes"
                        },
                        new
                        {
                            Id = new Guid("c7004893-0f89-467a-b6fe-37662f735bf1"),
                            Code = "ConfirmPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Parolayı Doğrula"
                        },
                        new
                        {
                            Id = new Guid("558003bf-4696-40d5-a8ed-9ba1d2d82701"),
                            Code = "ConfirmPassword",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Confirm Password"
                        },
                        new
                        {
                            Id = new Guid("86501228-939c-4b77-8593-3b0587cdd7dd"),
                            Code = "Code",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kod"
                        },
                        new
                        {
                            Id = new Guid("6cf53938-1b61-4c58-b1af-ed85fe0060b1"),
                            Code = "Code",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Code"
                        },
                        new
                        {
                            Id = new Guid("0890b6ce-ed6c-4813-870f-c8b22f5e6917"),
                            Code = "Alias",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Görünen Ad"
                        },
                        new
                        {
                            Id = new Guid("8cf00c5a-ad2a-48ad-af9f-90288eda9acd"),
                            Code = "Alias",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Alias"
                        },
                        new
                        {
                            Id = new Guid("bf3a355d-f6cf-4d86-be0a-ff16275cb054"),
                            Code = "Description",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Açıklama"
                        },
                        new
                        {
                            Id = new Guid("6a947e2d-edef-4845-ba08-3196d722ea93"),
                            Code = "Description",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Description"
                        },
                        new
                        {
                            Id = new Guid("29f273b3-d502-42e0-9f5d-ec6077e305d1"),
                            Code = "Value",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Değer"
                        },
                        new
                        {
                            Id = new Guid("3ea7820d-e7de-45a3-b13c-c4b391d3cbb4"),
                            Code = "Value",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Value"
                        },
                        new
                        {
                            Id = new Guid("1b05bf77-fff8-4d25-8794-514a00c8f94e"),
                            Code = "LangCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Dil Kodu"
                        },
                        new
                        {
                            Id = new Guid("8abf87b8-8a43-4cbc-aa65-916d0050a8b3"),
                            Code = "LangCode",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Lang Code"
                        },
                        new
                        {
                            Id = new Guid("0854c82f-0028-4035-b6b2-4b9f82fa7447"),
                            Code = "Name",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Adı"
                        },
                        new
                        {
                            Id = new Guid("e88a145d-cbe0-49c0-a654-2d07a7bf525a"),
                            Code = "Name",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Name"
                        },
                        new
                        {
                            Id = new Guid("b43c33d5-32d6-4903-ba03-425fe947bbb0"),
                            Code = "MobilePhones",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Cep Telefonu"
                        },
                        new
                        {
                            Id = new Guid("80277a61-bf6c-4eb4-b9fd-46a1bd933472"),
                            Code = "MobilePhones",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Mobile Phone"
                        },
                        new
                        {
                            Id = new Guid("8c078a6c-8897-4eaa-8f0d-b26e5608a219"),
                            Code = "NoRecordsFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kayıt Bulunamadı"
                        },
                        new
                        {
                            Id = new Guid("d18d0dec-2621-4b6c-8ff1-7f3316442ff3"),
                            Code = "NoRecordsFound",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "No Records Found"
                        },
                        new
                        {
                            Id = new Guid("5b6f85fc-c728-4689-9cce-7cee87283327"),
                            Code = "Required",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Bu alan zorunludur!"
                        },
                        new
                        {
                            Id = new Guid("1d6a9c7f-ae97-4b0d-9cac-deb807127738"),
                            Code = "Required",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "This field is required!"
                        },
                        new
                        {
                            Id = new Guid("8aaabb13-738d-4b93-bc46-b9ee596bd956"),
                            Code = "Permissions",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Permissions"
                        },
                        new
                        {
                            Id = new Guid("75a6c940-a341-4838-b2f6-cc851b4a41b1"),
                            Code = "Permissions",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "İzinler"
                        },
                        new
                        {
                            Id = new Guid("2233452b-652c-4173-93c3-615e1647b222"),
                            Code = "GroupList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Grup Listesi"
                        },
                        new
                        {
                            Id = new Guid("fa7e3ba4-fe3b-4894-8c7b-c45ca5952400"),
                            Code = "GroupList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Group List"
                        },
                        new
                        {
                            Id = new Guid("27d933d6-e2cf-42cb-8562-97d5b819d74f"),
                            Code = "GrupPermissions",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Grup Yetkileri"
                        },
                        new
                        {
                            Id = new Guid("3db92173-0d31-4922-ba21-514f54bee8b5"),
                            Code = "GrupPermissions",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Grup Permissions"
                        },
                        new
                        {
                            Id = new Guid("c4329a81-8a81-4287-b5eb-623db60248d0"),
                            Code = "Add",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Ekle"
                        },
                        new
                        {
                            Id = new Guid("e6b36020-0656-47f0-897f-330ae436d6e8"),
                            Code = "Add",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Add"
                        },
                        new
                        {
                            Id = new Guid("6005aa17-bab0-4762-9d32-58c84aab27f8"),
                            Code = "UserList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Kullanıcı Listesi"
                        },
                        new
                        {
                            Id = new Guid("d94081ec-22ea-4427-80ae-b1b3e38d8f67"),
                            Code = "UserList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "User List"
                        },
                        new
                        {
                            Id = new Guid("fc3dd97a-8bbe-46e0-90ea-667032e03505"),
                            Code = "OperationClaimList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Yetki Listesi"
                        },
                        new
                        {
                            Id = new Guid("cc9a2f36-78f7-4955-b18e-3ef1140e0f54"),
                            Code = "OperationClaimList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "OperationClaim List"
                        },
                        new
                        {
                            Id = new Guid("545572e0-6c8b-452d-8ae4-2399f983499b"),
                            Code = "LanguageList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Dil Listesi"
                        },
                        new
                        {
                            Id = new Guid("356c871c-6fb8-4234-8133-3ff0106ed81b"),
                            Code = "LanguageList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Language List"
                        },
                        new
                        {
                            Id = new Guid("b16e2a8c-3ebc-43ed-ad7d-aa6f1fa26bd4"),
                            Code = "TranslateList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Dil Çeviri Listesi"
                        },
                        new
                        {
                            Id = new Guid("05392f6f-2753-4c78-930c-8d78efe5a306"),
                            Code = "TranslateList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Translate List"
                        },
                        new
                        {
                            Id = new Guid("d9dc8181-7c40-41f0-a34b-8093c73bff33"),
                            Code = "LogList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "İşlem Kütüğü"
                        },
                        new
                        {
                            Id = new Guid("90469c8b-f0a6-4ed0-b2cf-2210456cd30f"),
                            Code = "LogList",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "LogList"
                        },
                        new
                        {
                            Id = new Guid("acb4782a-3d2e-4958-afae-f786d570b617"),
                            Code = "DeleteConfirm",
                            LangId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Value = "Emin misiniz?"
                        },
                        new
                        {
                            Id = new Guid("9b1b85ca-b5d8-4a84-9be0-7be5ad8ab8a6"),
                            Code = "DeleteConfirm",
                            LangId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Value = "Are you sure?"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<long>("CitizenId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2022, 8, 31, 0, 38, 0, 942, DateTimeKind.Local).AddTicks(2419));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("MobilePhones")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("MobilePhones");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id", "UserId", "ClaimId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserGroup", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Entities.Concrete.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("Pid")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
